name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - uses: LucasRoesler/openfaas-action/template_store_pull@master
      name: Fetch Template
      with:
        name: "python3-flask"
    - uses: LucasRoesler/openfaas-action/build@master
      name: Build
      with:
        path: "wordcount.yml"
        tag: "sha"
    - uses: LucasRoesler/openfaas-action/push@master
      name: Push image
      with:
        path: "wordcount.yml"
        tag: "sha"

